### ISSUE TITLE
changing language should change all language on the same page

### ISSUE THREAD

**Issue by narrator0** [LibreTexts/ckeditor-binder-plugin#3]
Currently it uses the first pre tag's `data-language` attribute as the language. So the author can insert below a different language which will not be used. Changing the language in the select box should change all language on the page.

**Comment by narrator0** [comment]
Maybe you can find a way to use a global config instead of getting the language from the HTML tags.

**Comment by celine168** [comment]
~~I still think that it's necessary to change the `data-language` of each tag because this tells CodeMirror which syntax highlighting to use.~~
Realized that once you insert into the editor, you technically don't need to re-edit it in CodeMirror. But I think it would still be confusing for the user if they switch to HTML and see different language tags everywhere.

**Comment by celine168** [comment]
I have a solution that uses the HTML tags to detect the language, but I do think that this is a "less safe" way of detecting languages. Ideally we should probably pass around a current thebelab configuration? 

Now, opening the dialog causes the kernel to restart, even if the language isn't changed. I think using a config would probably optimize this.
