### ISSUE TITLE
Matplotlib - JavaScript output is disabled in JupyterLab

### ISSUE THREAD

**Issue by jadeclan** [LibreTexts/ckeditor-binder-plugin#77]
As a user, am I able to enable JavaScript in JupyterLab that is hosted on LibreText? If so, how can this be done?  If there is documentation somewhere, please point me to it.

I am trying testing inserting python code with a non-interactive matplotlib 3d plot (code included below).  Once I get the initial test up, I hope to test interactive functionality, specifically value inputs, radio buttons, drop-down list, slider, save feature, ... ) 
```python
import matplotlib.pyplot as plt
import numpy as np
from mpl_toolkits.mplot3d import Axes3D
import mpl_toolkits.axes_grid1
%matplotlib notebook

pi = np.pi
lowerLimit = -2
upperLimit = 2
step = .01

eq = "1-x**2"

def f(x):
    return 1-x**2

xs = np.arange(lowerLimit, upperLimit+step, step)
ys = f(xs)
maximum = abs(ys).max()

fig = plt.figure('Volume Animated Circle Slices around X axis', figsize=(6,3))
ax1 = fig.gca(projection='3d')
plt.style.use('seaborn-pastel')
ax1.set_title('\nRegion under parabola ' + eq + '\n circular slices around x axis')

ax1.view_init(elev=45, azim=-90)

ax1.set_xlabel('X axis')
ax1.set_ylabel('Y axis')
ax1.set_zlabel('Z axis')

ax1.axes.set_xlim3d(lowerLimit,upperLimit)
ticks =  np.linspace(lowerLimit, upperLimit, 5)
ax1.axes.set_xticks(ticks)
ticks =  np.linspace(-maximum, maximum, 5)
ax1.axes.set_ylim3d(maximum, -maximum)
ax1.axes.set_yticks(ticks)
ax1.axes.set_zlim3d(-maximum, maximum)
ax1.axes.set_zticks(ticks)

for x in xs:
    theta = -pi
    a = []
    b = []
    c = []
    while theta <= pi:
        bx = np.cos(theta)*f(x)
        cx = np.sin(theta)*f(x)
        a.append(x)
        b.append(bx)
        c.append(cx)
        theta += pi/36.0
    
    circle, = ax1.plot3D(a, b, c, color='b')

plt.show()
```

**Comment by moorepants** [comment]
You'll need to remove the line `%matplotlib notebook`. That may fix it. If you want png plots in matplotlib it needs to use the agg backend (or another static backend).

Here is an explanation of how matplotlib and Jupyter work wrt to plotting: https://medium.com/@1522933668924/using-matplotlib-in-jupyter-notebooks-comparing-methods-and-some-tips-python-c38e85b40ba1

**Comment by moorepants** [comment]
> Once I get the initial test up, I hope to test interactive functionality, specifically value inputs, radio buttons, drop-down list, slider, save feature, ... )

Note that this will require https://github.com/jupyter-widgets/ipywidgets which I don't think we have quite working yet.

**Comment by moorepants** [comment]
It works for me without `%matplotlib notebook`.
![image](https://user-images.githubusercontent.com/276007/80749574-7a25f400-8adb-11ea-9fc5-0b41c424b283.png)

**Comment by moorepants** [comment]
If you want a JS version you'll need to use `%matplotlib widget`, which also works:
![image](https://user-images.githubusercontent.com/276007/80749784-ddb02180-8adb-11ea-98cf-b105a251055d.png)

**Comment by moorepants** [comment]
`%matplotlib notebook` is for the old Jupyter notebook interface, so I'm not sure we will support that.

**Comment by jadeclan** [comment]
Thanks for the quick response.  Replacing the %matplotlib notebook with
%matplotlib widget did the trick on both the static image that was produced
with the code I shared with you and code to create a simple animation
<https://math.libretexts.org/Courses/Mount_Royal_University/MATH_2200%3A_Calculus_for_Scientists_II/Solutions_and_Visuals_using_Python/Chapter_2/Chapter_1>.
Also on the same page(at the bottom) is an animation with working radio
button, text input boxes, simple animation controls.  When you think
ipywidgets are operational, you can test Button, Text and Output widget
functionality with this simple partial fraction solver
<https://math.libretexts.org/Courses/Mount_Royal_University/MATH_2200%3A_Calculus_for_Scientists_II/Solutions_and_Visuals_using_Python/Chapter_2/Partial_Fraction_Solver(not_operational)>.
Both these links are to LibreText pages and will only be available while
I'm getting organized with material.

I am using these pages as a playground to test algorithms - once I have a
few ready, I will ask Pamini (owner to the textbook) to help set up the
page structure so that it easier to use and looks better.

When you find the time, I am interested in the workflow, tools and methods
you use for Python programming. Specifically:

   - Do you use an IDE?  If so which one?
   - How do you hide the code on LibreText, so that there are words
   explaining what will happen when the "RUN" button is pressed rather than
   showing the implementation details (the Python code)?
   - How do you decorate the code using markdown to provide pretty
   documentation?
   - Are the Python code algorithms that I develop and place on a LibreText
   page independent (ie, if I set x=1 in algorithm 1, is x=1 in the second
   algorithm since they are on the same page)?  Or should each algorithm be
   placed on separate pages?

James

PS I am not sure of the desired structure of a response to your response to
my Github issue.  If this format/structure/content are not desirable, let
me know and I'll try to adjust in the future.

**Comment by jadeclan** [comment]
Link to Partial Fraction Solver
<https://math.libretexts.org/Courses/Mount_Royal_University/MATH_2200%3A_Calculus_for_Scientists_II/Solutions_and_Visuals_using_Python/Chapter_2/Partial_Fraction_Solver(not_operational)>.
Not sure why it wasn't saved the first time.
James

**Comment by moorepants** [comment]
James,

Very cool demos.

matplotlib has some builtin "widget" functionality which you seem to be using in the last example. I don't know the status of those working with ipympl (https://github.com/matplotlib/ipympl) which is what we have enabled. Calling `%matplotlib widget` is using ipympl. You'll have to see if it works and checkout the documentation of ipympl.

Cool to see you using SymPy, I am a SymPy core developer.

> When you find the time, I am interested in the workflow, tools and methods
you use for Python programming.

I can tell you what I do personally, but there are lots of options and preferences and the average person may not use my workflow.

> - Do you use an IDE?  If so which one?

No, not exactly. I use vim with some Python plugins. Popular Python IDEs are Spyder (matlab like), Vscode, Pycharm, JupyterLab.

 > How do you hide the code on LibreText, so that there are words
   explaining what will happen when the "RUN" button is pressed rather than
   showing the implementation details (the Python code)?

We have two checkboxes that let you hide the code or hide the output. If you hide the code, your figure should appear, but students won't be able to run the example. This still needs some work. I don't think this works with Javascript based outputs, but will with static matplotlib pngs. Another trick would be to write a python script that makes your figure and upload it to the libretexts page. Then you can download and execute the script in two lines.

```
!wget https://url/to/my-file.py
%run my-file.py
```

Please provide feedback on what your desired functionality is and we can try to implement it.

> - How do you decorate the code using markdown to provide pretty documentation?

I typically use the numpydoc format style for docstrings written in RestructuredText. Many tools, like sphinx, can then parse that and make nice HTML renderings. I think Sphinx may have a markdown option too. Markdown isn't really used in Python documentation though, since RST was around long before markdown.

> Are the Python code algorithms that I develop and place on a LibreText page independent (ie, if I set x=1 in algorithm 1, is x=1 in the second algorithm since they are on the same page)?  Or should each algorithm be placed on separate pages?

Every cell on the same page share a namespace. It is exactly like running a single shell session or single jupyter notebook. So, no, the code is not independent.

**Comment by moorepants** [comment]
This example works with `%matplotlib widget`.
