### ISSUE TITLE
Error: Expected linebreaks to be 'LF' but found 'CRLF' - yarn start command

### ISSUE THREAD

**Issue by sandertyu** [LibreTexts/ckeditor-binder-plugin#97]
All of the files in src/script yield an `'Expected linebreaks to be 'LF' but found 'CRLF''` error when the yarn start command is used. The error looks like this; 
![error](https://user-images.githubusercontent.com/59950537/83812795-faa6ba00-a670-11ea-982b-604d134ec02f.PNG)

I was able to locally fix the issue just by going into my VSCode and changing 'CRLF' to 'LF'. The error doesn't seem to inhibit the command from working properly, but it may have other effects. Posting here so the knowledge is saved.

**Comment by narrator0** [comment]
We can discuss if we want to remove that rule from es-lint. I personally would want to keep the line-breaks consistent on all systems because sometimes there will be issues when trying to parse text with mix line-breaks. One solution is to add a `.gitattributes` file to prevent git from converting line-breaks.

> see [here](https://eslint.org/docs/rules/linebreak-style#using-this-rule-with-version-control-systems) for more information.

**Comment by celine168** [comment]
I would personally want to keep them the line-breaks in the linter as well, for the same reasons.

**Comment by sandertyu** [comment]
I agree with using LF linebreaks. This is old and I was new and didn't know what they meant. We can close this now as it's not a problem.
